openapi: 3.0.2
info:
  title: Menu
  version: 0.0.1
  description: API definition of menu
  contact:
    name: creator's name
    url: http://creator.homepage.address
    email: creator@creator.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
paths:
  /menus:
    summary: Global operations on menus
    get:
      tags:
      - menus
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Menu'
              examples:
                menus_json:
                  value:
                  -
                    menuId: A string
                    menuName: A string
                    price: value
                    stockStatus: A string
                    availability: A string
          description: Get list of menus
      operationId: GetMenu
      summary: Get list of menus
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Menu'
            examples:
              1:
                value:
                  menuId: A string
                  menuName: A string
                  price: value
                  stockStatus: A string
                  availability: A string
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Menu'
              examples:
                1:
                  value:
                    menuId: A string
                    menuName: A string
                    price: value
                    stockStatus: A string
                    availability: A string
          description: Changed Menu
      operationId: Post Menu
      summary: Post Menu        
  /menus/{id}:
    summary: Specific operation on menus
    get:
      parameters:
      - examples:
          value:
            value: value
        name: id
        description: Menu name
        schema:
          type: string
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Menu'
              examples:
                1:
                  value:
                    menuId: A string
                    menuName: A string
                    price: value
                    stockStatus: A string
                    availability: A string
          description: menus with specified id
      operationId: GetMenuById
      summary: Get Menu by id
      description: Get Menu by id
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Menu'
            examples:
              1:
                value:
                  menuId: A string
                  menuName: A string
                  price: value
                  stockStatus: A string
                  availability: A string
        required: true
      parameters:
      - examples:
          1:
            value: 1
        name: 
        description: Menu name
        schema:
          type: string
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Menu'
              examples:
                1:
                  value:
                    menuId: A string
                    menuName: A string
                    price: value
                    stockStatus: A string
                    availability: A string
          description: Changed Menu
      operationId: PatchMenu
      summary: Patch existing Menu
    parameters:
    - name: id
      description: Menu id
      schema:
        type: string
      in: path
      required: true
components:
  schemas:
    Menu:
      title: Root Type for Menu
      description: The root of the Menu type's schema.
      type: object
      properties:
        menuId:
          description: menuId of this Menu
          type: string
        menuName:
          description: menuName of this Menu
          type: string
        price:
          description: price of this Menu
          type: string
        stockStatus:
          description: stockStatus of this Menu
          type: string
        availability:
          description: availability of this Menu
          type: string
tags:
  - name: Menu
    description: Menu resource
